### ISSUE TITLE
Syncing left the version of CERT feed marked as T

### ISSUE THREAD

**Issue by tgurr** [greenbone/greenbone-feed-sync#13]
After packaging and trying out the new sync script by running `su -c "greenbone-feed-sync --verbose" -s /bin/bash gvm` to sync all feeds ([gvmd.log](https://github.com/greenbone/greenbone-feed-sync/files/10578828/gvmd.log)), the CERT-Bund feed was left without any version information in GSA and marked as T:

![Screenshot_20230203_125322](https://user-images.githubusercontent.com/414984/216600104-d0f398e4-e4aa-4c07-a09d-dffe22177777.png)

I waited and monitored top until things were clearly done but GSA still displays the feed without version information.

Running just `su -c "greenbone-feed-sync --type cert --verbose" -s /bin/bash gvm`

```
Trying to acquire lock on /var/lib/gvm/feed-update.lock
Acquired lock on /var/lib/gvm/feed-update.lock
⠹ Downloading CERT-Bund data from rsync://feed.community.greenbone.net/community/vulnerability-feed/22.04/cert-data/ to /var/lib/gvm/cert-data
Releasing lock on /var/lib/gvm/feed-update.lock
```

 afterwards doesn't change anything.

`su -c "gvmd --rebuild" -s /bin/bash gvm` didn't help either.

Running the old script once `su -c "greenbone-feed-sync --type CERT" -s /bin/bash gvm` which was done in a breeze

```
Greenbone community feed server - http://feed.community.greenbone.net/
This service is hosted by Greenbone Networks - http://www.greenbone.net/

All transactions are logged.

If you have any questions, please use the Greenbone community portal. 
See https://community.greenbone.net for details.

By using this service you agree to our terms and conditions.

Only one sync per time, otherwise the source ip will be temporarily blocked.

receiving incremental file list
timestamp
             13 100%   12,70kB/s    0:00:00 (xfr#1, to-chk=0/1)

sent 71 bytes  received 111 bytes  364,00 bytes/sec
total size is 13  speedup is 0,07
```
brought back the version information nearly instantly.

![Screenshot_20230203_132404](https://user-images.githubusercontent.com/414984/216603080-9fedb616-453e-4f62-a965-879f2d3a457d.png)

**Comment by bjoernricks** [comment]
I am already on it :-) The feed.xml files are now generated via the feed deployment and I just need to push the fix for that.

**Comment by bjoernricks** [comment]
Should be in the feed with the next update (probably not before Monday 12h CET).

**Comment by y0urself** [comment]
This issue is also not related to the script. It seems, that it also occurs with the old feed sync script. Thank you for pointing it out, anyways! :)

**Comment by bjoernricks** [comment]
I guess the old script is also affected because the timestamp file was missing since we switched the cert-data source to WID-Sec.

**Comment by bjoernricks** [comment]
Should be fixed now 
![grafik](https://user-images.githubusercontent.com/897575/216999130-1fa0f858-c26c-4351-8140-f3203bbe0c36.png)
